services:
  # Backend API Service
  - type: web
    name: terminal-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && pip install -r backend/requirements.txt
    startCommand: python backend/main_production.py
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHON_VERSION
        value: 3.9.0
    healthCheckPath: /api/status

  # Frontend Service
  - type: web
    name: terminal-frontend
    env: static
    buildCommand: |
      cd frontend
      npm install
      npm run build
    staticPublishPath: frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https://terminal-backend.onrender.com
